---

- name: install bind9
  apt:
    cache_valid_time: 3600
    name: bind9
    state: latest
  register: bind_installed

- name: copy named.conf.local
  copy:
    src: named.conf.local
    dest: /etc/bind
  when: bind_installed.changed

- name: copy named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  when: bind_installed.changed

- name: copy db.neds
  template:
    src: db.neds.j2
    # we have to use this folder for dynamic zone because bind does not have permissions to write to /etc/bind
    dest: /var/lib/bind/db.neds
  when: bind_installed.changed

- name: restart BIND service
  systemd:
    name: bind9
    state: restarted
    enabled: true
  when: bind_installed.changed


- name: restart BIND service
  systemd:
    name: bind9
    state: restarted
    enabled: true
  when: bind_installed.changed


