---
- name: Ensure that all packages are configured
  shell: dpkg --configure -a
  ignore_errors: yes

- name: Update apt
  apt:
    update_cache: yes
    upgrade: "yes"
    cache_valid_time: 3600

- import_tasks: timezone.yml
- import_tasks: ntp.yml
- import_tasks: rngtools.yml
- import_tasks: admins.yml
  tags:
    - admins
  when: skip_admins is undefined or not skip_admins

- name: install openjdk
  become: true
  apt:
    name: openjdk-8-jre-headless
    state: latest

