---
- name: Set MySQL root password
  debconf:
    name: mysql-community-server
    question: mysql-community-server/root-pass
    value: root
    vtype: password

- name: Confirm MySQL root password
  debconf:
    name: mysql-community-server
    question: mysql-community-server/re-root-pass
    value: root
    vtype: password

- name: Enable Legacy Authentication Method
  debconf:
    name: mysql-community-server
    question: mysql-server/default-auth-override
    value: Use Legacy Authentication Method (Retain MySQL 5.x Compatibility)
    vtype: select

- name: Install/Update MySQL 8.0 Community Server
  apt:
    name: ['mysql-server-8.0', 'mysql-client', 'python3-pymysql']
    cache_valid_time: 3600
    state: latest
