- name: find sml hostname
  set_fact:
    sml_hostname: "{{ groups.bdmsl_servers.0 if using_lxd is undefined or not using_lxd else groups.bdmsl_servers.0 + '.lxd' }}"

- name: find sml ip (dig)
  set_fact:
    private_dns: "{{ lookup('dig', sml_hostname) }}"
  when: private_dns is undefined

- name: find sml ip (/etc/hosts)
  set_fact:
    private_dns: "{{ (lookup('file', '/etc/hosts').splitlines()|
                             list|
                             select('search', sml_hostname)|
                             list|
                             first).split().0 }}"
  when: private_dns is undefined or private_dns|length == 0 or private_dns == 'NXDOMAIN'

