- name: store smp hostname
  set_fact:
    smp_hostname: "{{ inventory_hostname if using_lxd is undefined or not using_lxd else inventory_hostname + '.lxd' }}"

- name: find smp ip (dig)
  set_fact:
    smp_ip : "{{ lookup('dig', smp_hostname) }}"

- name: find smp ip (/etc/hosts)
  set_fact:
    smp_ip: "{{ (lookup('file', '/etc/hosts').splitlines()|
                             list|
                             select('search', smp_hostname)|
                             list|
                             first).split().0 }}"
  when: smp_ip is undefined or smp_ip|length == 0 or smp_ip=='NXDOMAIN'
