---
- name: calculate hostname
  set_fact:
    full_hostname: "{{ inventory_hostname if using_lxd is undefined or not using_lxd else inventory_hostname + '.lxd' }}"

- name: generate keys and certificates if missing
  become: no
  command: "{{playbook_dir}}/neds_ca/generate_cert.sh {{full_hostname}}"
  delegate_to: 127.0.0.1

