---
- name: Ready lxd container
  become: yes
  delegate_to: 127.0.0.1
  lxd_container:
    name: "{{inventory_hostname}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: "focal"
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  register: lxdcreate
  when: using_lxd is defined and using_lxd
  tags:
    - ubuntu-container-init

- name: Add lxc containers to hosts file
  become: true
  delegate_to: 127.0.0.1
  lineinfile:
    path: /etc/hosts
    regexp: ".*{{inventory_hostname}}.lxd # automatically added by ansible"
    line: "{{lxdcreate.addresses.eth0.0}} {{inventory_hostname}}.lxd # automatically added by ansible"
  ignore_errors: true
  when: using_lxd is defined and using_lxd and lxdcreate.changed
