---
- name: Ready all containers
  with_inventory_hostnames: all:!lxd_servers
  lxd_container:
    name: "{{item}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: "focal"
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  register: lxdcreate
  tags:
    - ubuntu-container-init

- name: Add lxc containers to hosts file
  become: true
  with_items: "{{lxdcreate.results}}"
  lineinfile:
    path: /etc/hosts
    regexp: ".*{{item.item}}.lxd # automatically added by ansible"
    line: "{{item.addresses.eth0.0}} {{item.item}}.lxd # automatically added by ansible"
  ignore_errors: true
  when: lxdcreate.changed
