- hosts: localhost
  gather_facts: no
  roles:
    - role: local
  tasks:
    - name: check smp deb exists
      stat:
        path: "{{playbook_dir}}/../packaging/build/ubuntu20.04/harmony-smp_{{smp_version}}.ubuntu20.04_all.deb"
      register: smpdeb
      failed_when: not smpdeb.stat.exists

- hosts: niis_smp_servers
  gather_facts: no
  roles:
    - init-lxd

- hosts: niis_smp_servers
  become: yes
  pre_tasks:
    - import_tasks: tasks/find_sml_ip.yml
    - import_tasks: tasks/find_smp_ip.yml

  roles:
    - mock_cert
    - common
    - private_dns

  tasks:
    # needed for mysql ansible module
    - name: install PyMySQL
      apt:
        name: python3-pymysql
        state: present

    - name: set harmony-smp/integratewithsml
      debconf:
        name: harmony-smp
        question: harmony-smp/integratewithsml
        value: "true"
        vtype: boolean
    - name: set harmony-smp/smlurl
      debconf:
        name: harmony-smp
        question: harmony-smp/smlurl
        value: "http://{{sml_hostname}}:8080"
        vtype: string
    - name: set harmony-smp/smpurl
      debconf:
        name: harmony-smp
        question: harmony-smp/smpurl
        value: "https://{{smp_hostname}}:8443"
        vtype: string
    - name: set harmony-smp/smpip
      debconf:
        name: harmony-smp
        question: harmony-smp/smpip
        value: "{{smp_ip}}"
        vtype: string
    - name: set harmony-smp/adminuser
      debconf:
        name: harmony-smp
        question: harmony-smp/adminuser
        value: "admin"
        vtype: string
    - name: set harmony-smp/adminpassword
      debconf:
        name: harmony-smp
        question: harmony-smp/adminpassword
        value: "admin"
        vtype: password
      no_log: true

    - name: copy deb file
      copy:
        src: "{{playbook_dir}}/../packaging/build/ubuntu20.04/harmony-smp_{{smp_version}}.ubuntu20.04_all.deb"
        dest: /root/

    - name: install deb file
      apt:
        deb: "/root/harmony-smp_{{smp_version}}.ubuntu20.04_all.deb"
        state: present

    - name: delete smp keystore
      file:
        path: /etc/harmony-smp/smp-keystore.jks
        state: absent

    - name: replace smp keystore
      java_keystore:
        name: "{{ inventory_hostname }}"
        certificate: "{{lookup('file', playbook_dir + '/neds_ca/host_certs/' + smp_hostname + '.crt.pem') }}"
        private_key: "{{lookup('file', playbook_dir + '/neds_ca/host_certs/' + smp_hostname + '.key.pem') }}"
        password: password
        dest: /etc/harmony-smp/smp-keystore.jks
        owner: harmony_smp
        group: harmony_smp
        mode: 0600

    - name: copy truststore
      copy:
        src: "{{playbook_dir}}/neds_ca/neds-ca-trusted.jks"
        dest: /etc/harmony-smp/smp-truststore.jks
        force: yes
        owner: harmony_smp
        group: harmony_smp
        mode: 0600

    - name: change keystore and truststore passwords in db
      community.mysql.mysql_query:
        login_db: harmony_smp
        login_unix_socket: /var/run/mysqld/mysqld.sock
        query:
          - "UPDATE SMP_CONFIGURATION SET VALUE='{DEC}{password}', LAST_UPDATED_ON=NOW() WHERE PROPERTY='smp.keystore.password'"
          - "UPDATE SMP_CONFIGURATION SET VALUE='{DEC}{password}', LAST_UPDATED_ON=NOW() WHERE PROPERTY='smp.truststore.password'"

    - name: delete tls keystore
      file:
        path: /etc/harmony-smp/tls-keystore.jks
        state: absent

    - name: replace tls keystore
      java_keystore:
        name: "{{ inventory_hostname }}"
        certificate: "{{lookup('file', playbook_dir + '/neds_ca/host_certs/' + smp_hostname + '_tls.crt.pem') }}"
        private_key: "{{lookup('file', playbook_dir + '/neds_ca/host_certs/' + smp_hostname + '_tls.key.pem') }}"
        password: password
        dest: /etc/harmony-smp/tls-keystore.jks
        owner: harmony_smp
        group: harmony_smp
        mode: 0600

    - name: replace tls keystore password in server.xml
      lineinfile:
        path: /opt/harmony-smp/conf/server.xml
        regexp: "^\\s*keystorePass="
        line: "               keystorePass=\"password\""

    - name: enable and start harmony-smp
      service:
        name: harmony-smp
        enabled: true
        state: restarted

